spring:
  profiles:
    active: "dev"
---
server:
  port: 8081
###
#   Database Settings
###
spring:
  profiles: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:postgresql://localhost:5432/blockchain_users
    username:
    password:
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
# ===============================
# = MAIL configurations
# ===============================
  mail:
    host:
    username:
    password:
    port: 587

frontend:
  url: http://localhost:4200

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
        web: ERROR
      hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG