spring:
  profiles:
    active: "dev"
---
server:
  port: 8081
###
#   Database Settings
###
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:spring_boot_oauth2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username:
    password:
    driverClassName: org.h2.Driver
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open_in_view: true
    database: H2